# Generated by Django 5.1.4 on 2025-01-14 20:43

import edge_solutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background', models.FileField(upload_to=edge_solutions.models.solution_upload_handler)),
            ],
        ),
    ]
