# Generated by Django 5.1.4 on 2024-12-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_brokerage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='filename',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
