# Generated by Django 5.1.4 on 2025-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_brokerage', '0002_cover_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
